spring:
  application:
    name: awesome-cloud-ribbon
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 1000MB
server:
  port: 8766
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.51.100:8000/eureka/