spring:
  application:
    name: awesome-cloud-eureka-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/
    registry-fetch-interval-seconds: 2
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: debug
server:
  port: 8082
  servlet:
    context-path: /eureka-client
