spring:
  application:
    name: service-hi
server:
  port: 8762
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/