spring:
  application:
    name: awesome-cloud-eureka-client3
server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.51.100:8000/eureka/
  instance:
    prefer-ip-address: true