spring:
  application:
    name: awesome-cloud-sleuth
  zipkin:
    base-url: http://192.168.51.100:9010
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.51.100:8000/eureka/
  instance:
    prefer-ip-address: true


