spring:
  application:
    name: awesome-cloud-zipkin-client
#  zipkin:
#    base-url: http://192.168.51.100:9411

#  sleuth:
#    sampler:
#      probability: 1

server:
  port: 9412
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.51.100:8000/eureka/

#logging:
#  level:
#    org:
#      springframework:
#        web: debug
