version: '2'
services:
  eureka:
    build:
      context: eureka
      dockerfile: Dockerfile
    image: eureka:v1.0
    container_name: eureka
    ports:
      - "9000:9000"
    networks:
      - dev
    command: "java -Xmx64m -jar eureka.jar --server.port=9000"
  client:
    build:
      context: client
      dockerfile: Dockerfile
    image: client:v1.0
    ports:
      - "9001:9001"
    container_name: "client"
    networks:
      - dev
    command: "java -Xmx64m -jar client.jar --server.port=9001 --eureka.client.serviceUrl.defaultZone=http://192.168.0.103:9000/eureka/"
    depends_on:
      - eureka
networks:
  dev:
    driver: bridge
  pro:
    driver: bridge