version: '2'
services:
  eureka-server:
    build:
      context: eureka-server
      dockerfile: Dockerfile
    image: eureka-server:v1.0
    container_name: eureka-server
    ports:
      - "9000:9000"
    networks:
     - dev
    command: "java -Xmx64m -jar eureka.jar --server.port=9000 --eureka.instance.hostname=eureka-server"
  client:
    build:
      context: client
      dockerfile: Dockerfile
    image: client:v1.0
    ports:
      - "9001:9001"
    container_name: "client"
    networks:
      - dev
    command: "java -Xmx64m -jar client.jar --server.port=9001 --eureka.client.serviceUrl.defaultZone=http://172.21.0.2:9000/eureka/"
    depends_on:
      - eureka-server
networks:
  dev:
    driver: bridge
  pro:
    driver: bridge